# 20230322: Deleted metabase and nginx 
# !!!!!! I need to modify Jenkinsfile to run the build again in the future !!!!!!!!!!
version: '3.8' 

services:
  db:
    image: postgres
    # Changed the volumes from bind mount to volume mount (simpler to run through Jenkins pipeline)
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: catwatcher_test_user
      POSTGRES_PASSWORD: catwatcher_test_pw
      POSTGRES_DB: catwatcher_test_db
    ports: 
      - 5431:5432   # 5431 on the cattechserver might have been used by my experiment on setting up postgres and metabase with docker

  datawatcher:
    image: cat_data_watcher:latest
    volumes:
      - type: bind
        # ${WORKSPACE} and cat_watcher_output are added to run Jenkins
        # Changed from /var/nfs/cat_watcher_output for the convenience of running through Jenkins pipeline
        source: ${WORKSPACE}/cat_watcher_output 
        #source: ../cat_watcher_output # for testing without using Jenkins
        target: /usr/cat_watcher_output
      # 20221010: Added so that I can run unit tests inside of docker container
      - type: bind
        source: ${WORKSPACE}/test
        #source: ../test # for testing without using Jenkins
        target: /test
      - type: bind
        source: ${WORKSPACE}/CatDataSchema
        target: /CatDataSchema
    restart: always
    depends_on:
      - db
    environment:
      CAT_DATA_DMZ: /usr/cat_watcher_output  # This environment variable is called in cli.py
      DATABASE_URL: postgresql+psycopg2://catwatcher_test_user:catwatcher_test_pw@db:5432/catwatcher_test_db 
    # cat_data_migrate, cat_data_watcher is command line tool made available from using this image
    command: bash -c "sleep 5 && cat_data_watcher"   

volumes:
  db_data: