"""create_cat_data_table

Revision ID: 38342a1145ea
Revises: 
Create Date: 2022-07-29 14:45:43.903094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38342a1145ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_data',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Datetime', sa.Date(), nullable=True),
    sa.Column('Entry', sa.DateTime(), nullable=True),
    sa.Column('Depart', sa.DateTime(), nullable=True),
    sa.Column('Duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat_data')
    # ### end Alembic commands ###
